package com.integrity.lawCase.hostManage.bean;
// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Casedomainsituation generated by hbm2java
 */
public class DomainsituationObject  implements java.io.Serializable {


     private Long id;
     private Long hostId;//主机id
     private String objectName;//对象名称（主机名称）
     private String domain;//域名
     private String domainResolution;//域名解析机构
     private String domainResolutionServices;//域名解析服务器
     private String domainServiceProvider;//域名服务商
     private String regTime;//注册时间
     private String expiredTime;//过期时间
     private String databaseType;//数据库类型
     private String serviceType;//服务器类型
     private String developeLanguage;//开发语言
     private String remarkes;//备注
     private Date createTime;//创建时间
     private String remarkes1;
     private String remarkes2;
     private Integer remarkes3;

    public DomainsituationObject() {
    }

	
    public DomainsituationObject(Long id) {
        this.id = id;
    }
    public DomainsituationObject(Long id, Long hostId, String objectName, String domain, String domainResolution, String domainResolutionServices, String 
domainServiceProvider, String regTime, String expiredTime, String databaseType, String serviceType, String developeLanguage, String remarkes, Date createTime, String remarkes1, String remarkes2, Integer remarkes3) {
       this.id = id;
       this.hostId = hostId;
       this.objectName = objectName;
       this.domain = domain;
       this.domainResolution = domainResolution;
       this.domainResolutionServices = domainResolutionServices;
       this.domainServiceProvider = domainServiceProvider;
       this.regTime = regTime;
       this.expiredTime = expiredTime;
       this.databaseType = databaseType;
       this.serviceType = serviceType;
       this.developeLanguage = developeLanguage;
       this.remarkes = remarkes;
       this.createTime = createTime;
       this.remarkes1 = remarkes1;
       this.remarkes2 = remarkes2;
       this.remarkes3 = remarkes3;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getHostId() {
        return this.hostId;
    }
    
    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public String getDomainResolution() {
        return this.domainResolution;
    }
    
    public void setDomainResolution(String domainResolution) {
        this.domainResolution = domainResolution;
    }
    public String getDomainResolutionServices() {
        return this.domainResolutionServices;
    }
    
    public void setDomainResolutionServices(String domainResolutionServices) {
        this.domainResolutionServices = domainResolutionServices;
    }

    public String getDomainServiceProvider() {
		return domainServiceProvider;
	}
	public void setDomainServiceProvider(String domainServiceProvider) {
		this.domainServiceProvider = domainServiceProvider;
	}
	public String getRegTime() {
        return this.regTime;
    }
    
    public void setRegTime(String regTime) {
        this.regTime = regTime;
    }
    public String getExpiredTime() {
        return this.expiredTime;
    }
    
    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }
    public String getDatabaseType() {
        return this.databaseType;
    }
    
    public void setDatabaseType(String databaseType) {
        this.databaseType = databaseType;
    }
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    public String getDevelopeLanguage() {
        return this.developeLanguage;
    }
    
    public void setDevelopeLanguage(String developeLanguage) {
        this.developeLanguage = developeLanguage;
    }
    public String getRemarkes() {
        return this.remarkes;
    }
    
    public void setRemarkes(String remarkes) {
        this.remarkes = remarkes;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getRemarkes1() {
        return this.remarkes1;
    }
    
    public void setRemarkes1(String remarkes1) {
        this.remarkes1 = remarkes1;
    }
    public String getRemarkes2() {
        return this.remarkes2;
    }
    
    public void setRemarkes2(String remarkes2) {
        this.remarkes2 = remarkes2;
    }
    public Integer getRemarkes3() {
        return this.remarkes3;
    }
    
    public void setRemarkes3(Integer remarkes3) {
        this.remarkes3 = remarkes3;
    }

}


