package com.integrity.lawCase.hostManage.bean;

// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Casehosts generated by hbm2java
 */
public class HostsObject implements java.io.Serializable {

	private Long id;
	private String hostIp;//主机ip
	private String hostName;//主机名称
	private String hostType;//主机类型
	private String operateSystem;//操作系统
	private String provider;//提供商
	private String hostState;//主机状态
	private String responsiblePerson;//责任人
	private String importantLevel;//重要等级
	private String directions;//所属方向
	private String location;//地点
	private String controlState;//控制状态
	private String macAddress;//mac地址
	private String installationService;//安装服务
	private String descriptionContents;//描述
	private Date createTime;//创建时间
	private String remarkes1;
	private String remarkes2;
	private Integer remarkes3;

	public HostsObject() {
	}

	public HostsObject(Long id,String hostIp, String hostName, String hostType,
			String operateSystem, String provider, String hostState,
			String responsiblePerson, String importantLevel, String directions,
			String location, String controlState, String macAddress,
			String installationService, String descriptionContents,
			Date createTime, String remarkes1, String remarkes2,
			Integer remarkes3) {
		this.id = id;
		this.hostIp = hostIp;
		this.hostName = hostName;
		this.hostType = hostType;
		this.operateSystem = operateSystem;
		this.provider = provider;
		this.hostState = hostState;
		this.responsiblePerson = responsiblePerson;
		this.importantLevel = importantLevel;
		this.directions = directions;
		this.location = location;
		this.controlState = controlState;
		this.macAddress = macAddress;
		this.installationService = installationService;
		this.descriptionContents = descriptionContents;
		this.createTime = createTime;
		this.remarkes1 = remarkes1;
		this.remarkes2 = remarkes2;
		this.remarkes3 = remarkes3;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getHostIp() {
		return this.hostIp;
	}

	public void setHostIp(String hostIp) {
		this.hostIp = hostIp;
	}

	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public String getHostType() {
		return this.hostType;
	}

	public void setHostType(String hostType) {
		this.hostType = hostType;
	}

	public String getOperateSystem() {
		return this.operateSystem;
	}

	public void setOperateSystem(String operateSystem) {
		this.operateSystem = operateSystem;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getHostState() {
		return this.hostState;
	}

	public void setHostState(String hostState) {
		this.hostState = hostState;
	}

	public String getResponsiblePerson() {
		return this.responsiblePerson;
	}

	public void setResponsiblePerson(String responsiblePerson) {
		this.responsiblePerson = responsiblePerson;
	}

	public String getImportantLevel() {
		return this.importantLevel;
	}

	public void setImportantLevel(String importantLevel) {
		this.importantLevel = importantLevel;
	}

	public String getDirections() {
		return this.directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getControlState() {
		return this.controlState;
	}

	public void setControlState(String controlState) {
		this.controlState = controlState;
	}

	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public String getInstallationService() {
		return this.installationService;
	}

	public void setInstallationService(String installationService) {
		this.installationService = installationService;
	}

	public String getDescriptionContents() {
		return this.descriptionContents;
	}

	public void setDescriptionContents(String descriptionContents) {
		this.descriptionContents = descriptionContents;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemarkes1() {
		return this.remarkes1;
	}

	public void setRemarkes1(String remarkes1) {
		this.remarkes1 = remarkes1;
	}

	public String getRemarkes2() {
		return this.remarkes2;
	}

	public void setRemarkes2(String remarkes2) {
		this.remarkes2 = remarkes2;
	}

	public Integer getRemarkes3() {
		return this.remarkes3;
	}

	public void setRemarkes3(Integer remarkes3) {
		this.remarkes3 = remarkes3;
	}

}
