package com.integrity.lawCase.peopleManage.bean;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

/**
 * Documentnumberobject generated by hbm2java
 */
@SuppressWarnings("serial")
public class Documentnumberobject implements java.io.Serializable {

	private long dnid;
	private long poid;
	private String dnname;
	private String dntype;
	private String dnnumber;
	private String dnremark;

	public Documentnumberobject() {
	}


	public Documentnumberobject(long dnid, long poid,String dnname,
			String dntype, String dnnumber, String dnremark) {
		this.dnid = dnid;
		this.poid=poid;
		this.dnname = dnname;
		this.dntype = dntype;
		this.dnnumber = dnnumber;
		this.dnremark = dnremark;
	}


	public long getDnid() {
		return dnid;
	}


	public void setDnid(long dnid) {
		this.dnid = dnid;
	}


	public long getPoid() {
		return poid;
	}


	public void setPoid(long poid) {
		this.poid = poid;
	}

	public String getDnname() {
		return this.dnname;
	}

	public void setDnname(String dnname) {
		this.dnname = dnname;
	}

	public String getDntype() {
		return this.dntype;
	}

	public void setDntype(String dntype) {
		this.dntype = dntype;
	}

	public String getDnnumber() {
		return this.dnnumber;
	}

	public void setDnnumber(String dnnumber) {
		this.dnnumber = dnnumber;
	}

	public String getDnremark() {
		return this.dnremark;
	}

	public void setDnremark(String dnremark) {
		this.dnremark = dnremark;
	}

	public boolean equals(Object obj){
		if(!(obj instanceof Documentnumberobject)){
			return false;
		}else{
			Documentnumberobject dobject = (Documentnumberobject)obj;
			return new EqualsBuilder().appendSuper(super.equals(obj))
				.append(this.dnid, dobject.dnid)
				.append(this.poid, dobject.poid)
				.isEquals();
			}
		}

		public int hashCode(){
			return new HashCodeBuilder(-528253723, -475504089)
			.appendSuper(super.hashCode())
			.append(this.dnid)
			.append(this.poid)
			.toHashCode();
		}
		
}
