package com.integrity.lawCase.peopleManage.bean;

// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Peopleobject generated by hbm2java
 */
public class Peopleobject implements java.io.Serializable {

	private long id;
	private String pocnname;
	private String ponamespell;
	private String poenname;
	private String pocontrolstatus;
	private String poalias;
	private String posex;
	private Date pobirthday;
	private Date pocreateday;
	private String pocountry;
	private String ponational;
	private String pohukou;
	private String polocation;
	private String podutyman;
	private String popersonstatus;
	private String poimportantlevel;
	private String podirectionof;
	private String poimage;
	private String podescription;
	private String poremark;

	public Peopleobject() {
	}

	public Peopleobject(int id) {
		this.id = id;
	}

	public Peopleobject(long id, String pocnname, String ponamespell,
			String poenname, String pocontrolstatus, String poalias,
			String posex, Date pobirthday, Date pocreateday, String pocountry,
			String ponational, String pohukou, String polocation,
			String podutyman, String popersonstatus, String poimportantlevel,
			String podirectionof, String poimage, String podescription,
			String poremark) {
		this.id = id;
		this.pocnname = pocnname;
		this.ponamespell = ponamespell;
		this.poenname = poenname;
		this.pocontrolstatus = pocontrolstatus;
		this.poalias = poalias;
		this.posex = posex;
		this.pobirthday = pobirthday;
		this.pocreateday = pocreateday;
		this.pocountry = pocountry;
		this.ponational = ponational;
		this.pohukou = pohukou;
		this.polocation = polocation;
		this.podutyman = podutyman;
		this.popersonstatus = popersonstatus;
		this.poimportantlevel = poimportantlevel;
		this.podirectionof = podirectionof;
		this.poimage = poimage;
		this.podescription = podescription;
		this.poremark = poremark;
	}

	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPocnname() {
		return this.pocnname;
	}

	public void setPocnname(String pocnname) {
		this.pocnname = pocnname;
	}

	public String getPonamespell() {
		return this.ponamespell;
	}

	public void setPonamespell(String ponamespell) {
		this.ponamespell = ponamespell;
	}

	public String getPoenname() {
		return this.poenname;
	}

	public void setPoenname(String poenname) {
		this.poenname = poenname;
	}

	public String getPocontrolstatus() {
		return this.pocontrolstatus;
	}

	public void setPocontrolstatus(String pocontrolstatus) {
		this.pocontrolstatus = pocontrolstatus;
	}

	public String getPoalias() {
		return this.poalias;
	}

	public void setPoalias(String poalias) {
		this.poalias = poalias;
	}

	public String getPosex() {
		return this.posex;
	}

	public void setPosex(String posex) {
		this.posex = posex;
	}

	public Date getPobirthday() {
		return this.pobirthday;
	}

	public void setPobirthday(Date pobirthday) {
		this.pobirthday = pobirthday;
	}

	public Date getPocreateday() {
		return this.pocreateday;
	}

	public void setPocreateday(Date pocreateday) {
		this.pocreateday = pocreateday;
	}

	public String getPocountry() {
		return this.pocountry;
	}

	public void setPocountry(String pocountry) {
		this.pocountry = pocountry;
	}

	public String getPonational() {
		return this.ponational;
	}

	public void setPonational(String ponational) {
		this.ponational = ponational;
	}

	public String getPohukou() {
		return this.pohukou;
	}

	public void setPohukou(String pohukou) {
		this.pohukou = pohukou;
	}

	public String getPolocation() {
		return this.polocation;
	}

	public void setPolocation(String polocation) {
		this.polocation = polocation;
	}

	public String getPodutyman() {
		return this.podutyman;
	}

	public void setPodutyman(String podutyman) {
		this.podutyman = podutyman;
	}

	public String getPopersonstatus() {
		return this.popersonstatus;
	}

	public void setPopersonstatus(String popersonstatus) {
		this.popersonstatus = popersonstatus;
	}

	public String getPoimportantlevel() {
		return this.poimportantlevel;
	}

	public void setPoimportantlevel(String poimportantlevel) {
		this.poimportantlevel = poimportantlevel;
	}

	public String getPodirectionof() {
		return this.podirectionof;
	}

	public void setPodirectionof(String podirectionof) {
		this.podirectionof = podirectionof;
	}

	public String getPoimage() {
		return this.poimage;
	}

	public void setPoimage(String poimage) {
		this.poimage = poimage;
	}

	public String getPodescription() {
		return this.podescription;
	}

	public void setPodescription(String podescription) {
		this.podescription = podescription;
	}

	public String getPoremark() {
		return this.poremark;
	}

	public void setPoremark(String poremark) {
		this.poremark = poremark;
	}

}
