package com.integrity.lawCase.hostManage.bean;

import java.util.Date;

// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

/**
 * Caseloopholes generated by hbm2java
 */
public class LoopholesObject implements java.io.Serializable {

	private Long id;
	private Long hostId;//主机id
	private String objectName;//对象名称（主机名称）
	private String authorityType;//权限类型
	private String vulnerabilityDescription;//漏洞描述
	private String methods;//利用方法
	private String useTools;//利用工具
	private String hiddenDoor;//隐藏后门
	private String remarks;//备注
	private Date createTime;//创建时间

	public LoopholesObject() {
	}

	public LoopholesObject(Long id) {
		this.id = id;
	}

	public LoopholesObject(Long id, Long hostId, String objectName,
			String authorityType, String vulnerabilityDescription,
			String methods, String useTools, String hiddenDoor, String remarks,Date createTime) {
		this.id = id;
		this.hostId = hostId;
		this.objectName = objectName;
		this.authorityType = authorityType;
		this.vulnerabilityDescription = vulnerabilityDescription;
		this.methods = methods;
		this.useTools = useTools;
		this.hiddenDoor = hiddenDoor;
		this.remarks = remarks;
		this.createTime = createTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getHostId() {
		return this.hostId;
	}

	public void setHostId(Long hostId) {
		this.hostId = hostId;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getAuthorityType() {
		return this.authorityType;
	}

	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType;
	}

	public String getVulnerabilityDescription() {
		return this.vulnerabilityDescription;
	}

	public void setVulnerabilityDescription(String vulnerabilityDescription) {
		this.vulnerabilityDescription = vulnerabilityDescription;
	}

	public String getMethods() {
		return this.methods;
	}

	public void setMethods(String methods) {
		this.methods = methods;
	}

	public String getUseTools() {
		return this.useTools;
	}

	public void setUseTools(String useTools) {
		this.useTools = useTools;
	}

	public String getHiddenDoor() {
		return this.hiddenDoor;
	}

	public void setHiddenDoor(String hiddenDoor) {
		this.hiddenDoor = hiddenDoor;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	

}
