package com.integrity.lawCase.peopleManage.bean;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

/**
 * Phonenumberobject generated by hbm2java
 */
public class Phonenumberobject implements java.io.Serializable {

	private long pnid;
	private long poid;
	private String pntype;
	private String pnname;
	private String pnnumber;
	private String pnremark;

	public Phonenumberobject() {
	}



	public Phonenumberobject(long pnid, long poid, String pntype, String pnname,
			String pnnumber, String pnremark) {
		this.pnid = pnid;
		this.poid = poid;
		this.pntype = pntype;
		this.pnname = pnname;
		this.pnnumber = pnnumber;
		this.pnremark = pnremark;
	}



	public long getPnid() {
		return pnid;
	}



	public void setPnid(long pnid) {
		this.pnid = pnid;
	}



	public long getPoid() {
		return poid;
	}



	public void setPoid(long poid) {
		this.poid = poid;
	}



	public String getPntype() {
		return this.pntype;
	}

	public void setPntype(String pntype) {
		this.pntype = pntype;
	}

	public String getPnname() {
		return this.pnname;
	}

	public void setPnname(String pnname) {
		this.pnname = pnname;
	}

	public String getPnnumber() {
		return this.pnnumber;
	}

	public void setPnnumber(String pnnumber) {
		this.pnnumber = pnnumber;
	}

	public String getPnremark() {
		return this.pnremark;
	}

	public void setPnremark(String pnremark) {
		this.pnremark = pnremark;
	}
	public boolean equals(Object obj){
		if(!(obj instanceof Phonenumberobject)){
			return false;
		}else{
			Phonenumberobject phonenumberobject = (Phonenumberobject)obj;
			return new EqualsBuilder().appendSuper(super.equals(obj))
				.append(this.pnid, phonenumberobject.pnid)
				.append(this.poid, phonenumberobject.poid)
				.isEquals();
			}
		}

		public int hashCode(){
			return new HashCodeBuilder(-528253723, -475504089)
			.appendSuper(super.hashCode())
			.append(this.pnid)
			.append(this.poid)
			.toHashCode();
		}
}
