package com.integrity.lawCase.peopleManage.bean;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


// Generated 2015-11-30 18:47:12 by Hibernate Tools 3.4.0.CR1

/**
 * Peoplevirtualobject generated by hbm2java
 */
@SuppressWarnings("serial")
public class Peoplevirtualobject implements java.io.Serializable {

	private long pvid;
	private long poid;
	private String pvname;
	private String pvaccounttype;
	private String pvusername;
	private String pvcontrolstatus;
	private String pvcontrolmeasures;
	private String pvpassword;
	private String pvloginaddress;
	private String pvremark;

	public Peoplevirtualobject() {
	}

	public Peoplevirtualobject(long pvid, long poid, String pvname,
			String pvaccounttype, String pvusername, String pvcontrolstatus,
			String pvcontrolmeasures, String pvpassword, String pvloginaddress,
			String pvremark) {
		this.pvid = pvid;
		this.poid = poid;
		this.pvname = pvname;
		this.pvaccounttype = pvaccounttype;
		this.pvusername = pvusername;
		this.pvcontrolstatus = pvcontrolstatus;
		this.pvcontrolmeasures = pvcontrolmeasures;
		this.pvpassword = pvpassword;
		this.pvloginaddress = pvloginaddress;
		this.pvremark = pvremark;
	}

	public long getPvid() {
		return pvid;
	}

	public void setPvid(long pvid) {
		this.pvid = pvid;
	}

	public long getPoid() {
		return poid;
	}

	public void setPoid(long poid) {
		this.poid = poid;
	}

	public String getPvname() {
		return this.pvname;
	}

	public void setPvname(String pvname) {
		this.pvname = pvname;
	}

	public String getPvaccounttype() {
		return this.pvaccounttype;
	}

	public void setPvaccounttype(String pvaccounttype) {
		this.pvaccounttype = pvaccounttype;
	}

	public String getPvusername() {
		return this.pvusername;
	}

	public void setPvusername(String pvusername) {
		this.pvusername = pvusername;
	}

	public String getPvcontrolstatus() {
		return this.pvcontrolstatus;
	}

	public void setPvcontrolstatus(String pvcontrolstatus) {
		this.pvcontrolstatus = pvcontrolstatus;
	}

	public String getPvcontrolmeasures() {
		return this.pvcontrolmeasures;
	}

	public void setPvcontrolmeasures(String pvcontrolmeasures) {
		this.pvcontrolmeasures = pvcontrolmeasures;
	}

	public String getPvpassword() {
		return this.pvpassword;
	}

	public void setPvpassword(String pvpassword) {
		this.pvpassword = pvpassword;
	}

	public String getPvloginaddress() {
		return this.pvloginaddress;
	}

	public void setPvloginaddress(String pvloginaddress) {
		this.pvloginaddress = pvloginaddress;
	}

	public String getPvremark() {
		return this.pvremark;
	}

	public void setPvremark(String pvremark) {
		this.pvremark = pvremark;
	}
	public boolean equals(Object obj){
		if(!(obj instanceof Peoplevirtualobject)){
			return false;
		}else{
			Peoplevirtualobject peoplevirtualobject = (Peoplevirtualobject)obj;
			return new EqualsBuilder().appendSuper(super.equals(obj))
				.append(this.pvid, peoplevirtualobject.pvid)
				.append(this.poid, peoplevirtualobject.poid)
				.isEquals();
			}
		}

		public int hashCode(){
			return new HashCodeBuilder(-528253723, -475504089)
			.appendSuper(super.hashCode())
			.append(this.pvid)
			.append(this.poid)
			.toHashCode();
		}
}
